[build]
  # Directory to change to before starting a build
  base = "frontend/"
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "build/"
  
  # Default build command
  command = "npm run build"

[build.environment]
  # Node version for build
  NODE_VERSION = "18"
  # Disable treating warnings as errors in CI
  CI = "false"
  # Production API URL
  REACT_APP_API_URL = "https://e-commerce-website-us30.onrender.com"
  # Your Netlify URL for CORS configuration
  FRONTEND_URL = "https://your-netlify-app.netlify.app"

# Redirect rules for single-page applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
